### ISSUE TITLE
Adding a build

### ISSUE THREAD

**Issue by Euregan** [web-auth/webauthn-helper#4]
Hello,
Is there any plan to add a build to this lib? This would allow easier usage of it, since it's bad practice to build external dependencies. I can submit a PR if you want

**Comment by Spomky** [comment]
Hi @Euregan,

That’s a nice idea!
As I am not comfortable with such behaviour, yes please if you have time, feel free to submit a PR.

**Comment by Euregan** [comment]
Sure then, I'll do that. 
Do you want me to throw a Travis build configuration file along with it?

**Comment by Spomky** [comment]
Hi @Euregan,

I correctly configured Github Actions and now the packages will be [automatically deployed](https://github.com/web-auth/webauthn-helper/packages).
Thank you for your help! I now close this issue. Feel free to open it if necessary.

As you may have noticed, the version is still `0.x.y` meaning it is considered as non-stable.
If you have any idea like this one or if you see features that are missing for the moment, I will be happy to merge them and mark it as stable.

Many thanks.
Regards

**Comment by Euregan** [comment]
Great, I'll let you know if I get some new wild idea :D
Thanks for the quick merge

**Comment by Euregan** [comment]
Actually, the actions are missing the `npm`/`yarn run build` command, which means the published package misses the `dist` folder

**Comment by Spomky** [comment]
Hell @Euregan,

Sorry for the inconvenience. It is now fixed and the `dist` folder is part of the published package.

Regards

**Comment by Euregan** [comment]
Awesome, thanks for the quick fix 🙂
